# Generated by Django 3.2 on 2023-03-02 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DegradomeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataSet', models.CharField(max_length=200)),
                ('Tissue', models.CharField(max_length=200)),
                ('Transcript_ID', models.CharField(max_length=200)),
                ('BLAST_ATH_protein', models.CharField(max_length=200)),
                ('Category', models.IntegerField()),
                ('Cleavage_Position', models.IntegerField()),
                ('miRNA_ID', models.CharField(max_length=200)),
                ('FM_miRNA', models.FloatField()),
                ('x5BL_miRNA', models.FloatField()),
                ('x5BP_miRNA', models.FloatField()),
                ('x5BS_miRNA', models.FloatField()),
                ('FM_target', models.FloatField()),
                ('x5BL_target', models.FloatField()),
                ('x5BP_target', models.FloatField()),
                ('x5BS_target', models.FloatField()),
                ('miRNA_aligned_fragment', models.CharField(max_length=200)),
                ('alignment', models.CharField(max_length=200)),
                ('Target_aligned_fragment', models.CharField(max_length=200)),
                ('Target_Desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pumps', models.CharField(choices=[('L', 'Log'), ('E', 'Erro'), ('O', 'Other')], max_length=1)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
    ]
