# Generated by Django 3.2 on 2023-03-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_degradomeresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degradomeresult',
            options={'managed': True},
        ),
    ]
