# Generated by Django 3.2 on 2023-03-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_v3deg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V3Deg',
        ),
    ]
