# Generated by Django 3.2 on 2023-03-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_v3deg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Degradomeresult',
        ),
    ]
