# Generated by Django 3.2 on 2023-03-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_delete_degradomeresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degradomeresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(db_column='DataSet', max_length=100, verbose_name='DataSet')),
                ('tissue', models.CharField(db_column='Tissue', max_length=100, verbose_name='Tissue')),
                ('transcript_id', models.CharField(db_column='Transcript_ID', max_length=100, verbose_name='Transcript_ID')),
                ('blast_ath_protein', models.CharField(db_column='BLAST_ATH_protein', max_length=100, verbose_name='BLAST_ATH_protein')),
                ('category', models.CharField(db_column='Category', max_length=100, verbose_name='Category')),
                ('cleavage_position', models.FloatField(db_column='Cleavage_Position', verbose_name='Cleavage_Position')),
                ('mirna_id', models.CharField(db_column='miRNA_ID', max_length=100, verbose_name='miRNA_ID')),
                ('fm_mirna', models.FloatField(db_column='FM_miRNA', verbose_name='FM_miRNA')),
                ('number_5bl_mirna', models.FloatField(db_column='5BL_miRNA', verbose_name='5BL_miRNA')),
                ('number_5bp_mirna', models.FloatField(db_column='5BP_miRNA', verbose_name='5BP_miRNA')),
                ('number_5bs_mirna', models.FloatField(db_column='5BS_miRNA', verbose_name='5BS_miRNA')),
                ('fm_target', models.FloatField(db_column='FM_target', verbose_name='FM_target')),
                ('number_5bl_target', models.FloatField(db_column='5BL_target', verbose_name='5BL_target')),
                ('number_5bp_target', models.FloatField(db_column='5BP_target', verbose_name='5BP_target')),
                ('number_5bs_target', models.FloatField(db_column='5BS_target', verbose_name='5BS_target')),
                ('mirna_aligned_fragment', models.CharField(db_column='miRNA_aligned_fragment', max_length=100, verbose_name='miRNA_aligned_fragment')),
                ('alignment', models.CharField(max_length=100)),
                ('target_aligned_fragment', models.CharField(db_column='Target_aligned_fragment', max_length=100, verbose_name='Target_aligned_fragment')),
                ('target_desc', models.CharField(db_column='Target_Desc', max_length=5000, verbose_name='Target_Desc')),
            ],
            options={
                'db_table': 'DegradomeResult',
                'managed': False,
            },
        ),
    ]
