# Generated by Django 3.2 on 2023-03-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_degradomeresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='v3deg',
            options={'managed': False},
        ),
    ]
