# Generated by Django 3.2 on 2023-03-12 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_alter_v3deg_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='V3Deg',
        ),
    ]
