# Generated by Django 3.2 on 2023-03-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phal_db_n2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='v3deg',
            options={'managed': True},
        ),
    ]
