# Generated by Django 3.2 on 2023-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phal_db_n2', '0003_auto_20230312_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v3deg',
            name='django_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='django_id'),
        ),
    ]
