# Generated by Django 3.2 on 2023-03-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phal_db_n2', '0004_alter_v3deg_django_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='v3deg',
            name='django_id',
        ),
        migrations.AddField(
            model_name='v3deg',
            name='id',
            field=models.BigAutoField(auto_created=True, db_column='Django_id', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
